name: Run Node Server

on: [push, pull_request]

jobs:
  run-node-server:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Run server
      run: node server.js
